# env: coin_game # coin_game or prisonner_dilemma
env: ipd
train_iterations: 10000
batch_size: 10
log_freq: 10
lr: 0.01
lr_im: 0.01
max_steps: 30
policy_a_arch: mlp
policy_b_arch: mlp
arch_a: {}
arch_b: {}
