# env: coin_game # coin_game or prisonner_dilemma
env:  coin_game
history: 3 # Int or None
train_iterations: 10000
batch_size: 50
log_freq: 10
lr: 0.01
lr_im: 0.01
max_steps: 100
policy_a_arch: mlp # mlp, rnn
policy_b_arch: mlp
arch_a: {}
arch_b: {}
