# env: coin_game # coin_game or prisonner_dilemma
env:  coin_game
history: 5 # Int or None
train_iterations: 10000
batch_size: 150
log_freq: 10
video_freq: 20
lr: 0.005
lr_im: 0.9
max_steps: 40
policy_a_arch: rnn # mlp, rnn
policy_b_arch: rnn
arch_a: {}
arch_b: {}
